feat(intro,game): intro,game작성화면 및 상세페이지
Sul-Game-Wiki/Sul-Game-Frontend pull request #13
Opened 2024-07-11 12:53 UTC by daye200

저를 많이 혼내주십쇼!!!!!!!

2024-07-11 12:59 UTC, daye200 reviewed
코멘트 제목

2024-07-11 12:59 UTC, daye200 commented on app/src/main/res/drawable/circle_white.xml
> +        <corners android:radius="20dp"/>
사각형 둥근모양

2024-07-11 12:59 UTC, daye200 commented on app/src/main/AndroidManifest.xml
>      tools:targetApi="31">
Test 메시지입니다 ^0^

2024-07-12 07:05 UTC, hwan04 requested changes

2024-07-12 07:05 UTC, hwan04 commented on app/src/main/res/layout/comment_list_item.xml
> +    android:id="@+id/textView5"
tv5_comment_item으로 아이디 변경 부탁드립니다

2024-07-13 09:23 UTC, hwan04 commented on app/src/main/res/drawable/circle_white.xml
> +        <corners android:radius="20dp"/>
이미 roundedbox로 drawable에 만들어 놨습니다.

2024-07-13 09:24 UTC, hwan04 requested changes

2024-07-13 09:24 UTC, hwan04 commented on app/src/main/res/layout/activity_gamecreate.xml
변수이름 통일시켜주세요.

2024-07-13 09:24 UTC, hwan04 commented on app/src/main/res/layout/activity_introcreate.xml
변수이름 통일시켜주세요.

2024-07-13 09:24 UTC, hwan04 commented on app/src/main/res/layout/activity_gamedetail.xml
변수이름 통일시켜주세요.

2024-07-15 10:36 UTC, cloudyGaha commented on app/src/main/res/drawable/circle_white.xml
> +        <corners android:radius="20dp"/>
***/drawable/roundedbox.xml***랑 겹치는 것 같은데 이름 수정해서 통합하는 것이 좋을 듯 합니다

2024-07-15 13:25 UTC, merged