feat(main): xml 디자인 및 기능구현, 서버연결(일부)
Sul-Game-Wiki/Sul-Game-Frontend pull request #22
Opened 2024-08-28 01:58 UTC by hwan04

2024-09-04 01:46 UTC, Cassiiopeia requested changes
"university"와 "college"는 둘 다 대학교를 나타낼 때 사용될 수 있는 변수 이름입니다. 그러나 어떤 것을 사용할지는 문맥에 따라 다를 수 있습니다:

university: 주로 4년제 대학이나 대학원, 종합대학교를 의미하는 경우에 사용됩니다. 일반적으로 학사, 석사, 박사 과정을 포함한 다양한 학위 프로그램을 제공하는 대학교를 가리킵니다.

college: 미국에서는 주로 2년제 대학이나 특정 학부를 의미할 수 있습니다. 영국 등 다른 나라에서는 종종 '대학'과 같은 의미로 사용되기도 합니다.

따라서 변수명을 선택할 때, 당신이 말하려는 학교가 주로 4년제 대학이나 대학원 프로그램을 제공하는 종합적인 기관을 나타내고자 한다면 university가 더 적합할 것입니다. 반면, 좀 더 일반적이거나 학부 중심의 학교를 나타내려는 경우라면 college도 사용할 수 있습니다.

예를 들어:

val universityName: String (대학교 이름)
val collegeName: String (학부나 2년제 대학 이름)
대학이 종합대학교인 경우에는 university를 사용하는 것이 더 일반적이고 명확할 것입니다.

라고 GPT행님이 이야기 하네요

대학교니까 school 이라는 표현보다

university라는 표현을 사용합시다

2024-09-04 01:46 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/SignUpActivity.kt
> +     * TODO : 서버랑 합체해야됨
합체~~ 끼얏호우~

2024-09-04 01:46 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/SignUpActivity.kt
> +    }
이거 다예 코드도 똑같이 말했는데 

boolean 값 표현할떄 

변수이름법을 통일할 필요가있어보여요

isNameAvailable 처럼 (예시임)  boolean 타입은 is로 시작하는걸로 하는거 어떤가요?

2024-09-04 01:46 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/SignUpActivity.kt
> +    private fun buttonClickable() {
이것도 is 붙여야되나  validation하는거니까 validate 하거나 check하거나

일단 메서드 이름이 좀더 정확했음 좋겠구요

2024-09-04 01:46 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/SignUpActivity.kt
> +                showUnderageDialog()
school은 선택사항이고

학교 비공개 체크박스 버튼 추가해야할것같아요

2024-09-04 01:46 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/SignUpActivity.kt
> +        }
이거 그냥 따로 adapt 안해도 커스텀으로 입력해도 그 입력값대로 보내주죠?

리스트에 없는 school 적어도 상관없는거죠??

아래에서도 얘기했지만 대학교 비공개 체크박스 추가좀요

api post요청할때 isUniversityVisible 라는 항목 boolean값 받을께요

2024-09-05 00:38 UTC, daye200 commented on app/src/main/java/com/example/sul_game_frontend_practice1/SignUpActivity.kt
> +        binding.etDateSignup.isFocusable = false
그냥 궁금해서 그런디 이거 xml에 작성하지 않고 여기다가 작성한 이유가 뭐야

2024-09-05 00:38 UTC, daye200 commented on app/src/main/java/com/example/sul_game_frontend_practice1/recyclerview/DrinkingGame/DrinkingGameAdapter.kt
> +    @SuppressLint("SetTextI18n")
이건뭐야?

2024-09-05 03:21 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/recyclerview/DrinkingGame/DrinkingGameAdapter.kt
> +    @SuppressLint("SetTextI18n")
그러게 이거뭐야? 안드로이드도 어노테이션 쓰는구나

2024-09-07 02:21 UTC, hwan04 commented on app/src/main/java/com/example/sul_game_frontend_practice1/SignUpActivity.kt
> +                showUnderageDialog()
바꿔놓겠습니당

2024-09-07 02:21 UTC, hwan04 commented on app/src/main/java/com/example/sul_game_frontend_practice1/SignUpActivity.kt
> +        }
리스트에 없는 학교 적으면 안 넘어가지도록 설정했는데 그냥 리스트에 없는 학교 입력해도 넘어가지도록 설정할까요?

2024-09-07 02:24 UTC, hwan04 commented on app/src/main/java/com/example/sul_game_frontend_practice1/SignUpActivity.kt
> +    }
boolean 타입을 리턴해주는 함수나 변수들에는 is로 다 통일시키겟습니다

2024-09-07 02:26 UTC, hwan04 commented on app/src/main/java/com/example/sul_game_frontend_practice1/recyclerview/DrinkingGame/DrinkingGameAdapter.kt
> +    @SuppressLint("SetTextI18n")
텍스트 바로 넣지 말라고 밑줄 띄워주는거 보기 싫어서 저거 추가해줬었는데 굳이 쓸 필요 없기는 한데 지울까용?

2024-09-07 09:30 UTC, hwan04 commented on app/src/main/java/com/example/sul_game_frontend_practice1/SignUpActivity.kt
> +     * TODO : 서버랑 합체해야됨
??!@?@?!?!?!

2024-09-07 09:31 UTC, hwan04 commented on app/src/main/java/com/example/sul_game_frontend_practice1/SignUpActivity.kt
> +        binding.etDateSignup.isFocusable = false
첨 xml은 기본 디자인이나 그런 것들로만 세팅하고 싶어서 여기다가 넣었습니다

2024-09-08 13:36 UTC, daye200 commented on app/src/main/java/com/example/sul_game_frontend_practice1/recyclerview/DrinkingGame/DrinkingGameAdapter.kt
> +    @SuppressLint("SetTextI18n")
필요하다고 생각하면 냅두고 필요없다고 생각하면 지우세용~

2024-09-08 15:13 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/SignUpActivity.kt
> +        }
흠 뭐가좋을까요 전 그래도 넘어갔으면하는디

2024-09-10 23:33 UTC, Cassiiopeia reviewed
굿굿

2024-09-10 23:33 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/LoginActivity.kt
> +        if (refreshToken.isNotEmpty()) {
결국... ㅠ

2024-09-10 23:33 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/LoginActivity.kt
> +                // TODO: 다음 화면으로 이동하는 로직 추가
메인화면으로 이동?

2024-09-10 23:33 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/SignUpActivity.kt
> +            if(binding.etNameSignup.text.toString() == previousName && previousName != ""){
이거 로그인할때받은 nickName 가져와서 띄워주는거맞나요??

2024-09-10 23:33 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/SignUpActivity.kt
> +            if(binding.etNameSignup.text.toString() == previousName && previousName != ""){
이메일도  고정시켜서 누를수없게하고 표시하는거 있나요?

2024-09-10 23:33 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/SignUpActivity.kt
> +    private fun isAvailableName(name: String): Boolean {
하세요...

2024-09-10 23:33 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/dialog/DateDialog.kt
> +package com.example.sul_game_frontend_practice1.dialog
이거 왜아직도 이런가요

2024-09-10 23:33 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/dialog/DateDialog.kt
> +    private fun isLeapYear(year: Int): Boolean {
이런거 따로 확인도 해야함? ㄷㄷ

2024-09-10 23:33 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/dialog/ModalBottomSheetDialog.kt
> +    private fun getInitialSound(text: String): String {
오호

2024-09-10 23:33 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/recyclerview/University/UniversityAdapter.kt
> +        } else {
else 사용하지마셔요

이렇게 else쓰면 조건이 뭔지 몰라요

else if 사용해두세요 가독성때문에

스위치문이랑 else  최대한 노사용 부탁

2024-09-10 23:33 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/retrofit/Member.kt
> +data class Intro(
좀 바뀌었습니다전체적으로 다시확인해야함

2024-09-12 07:56 UTC, merged