feat(create):create관련 여러기능추가
Sul-Game-Wiki/Sul-Game-Frontend pull request #24
Opened 2024-09-03 15:16 UTC by daye200

2024-09-04 01:30 UTC, Cassiiopeia requested changes

2024-09-04 01:30 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/create/CreateCreate.kt
> +    }
근데 이런 파일 확장자 유효성 검사로직은 다른 곳에서 사용할수있지않나요??

Util 적인 요소가 강한데 공통된폴더에서 FileUtil 이름으로 따로 파일 만들어놓은곳은 없나요??

2024-09-04 01:30 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/create/CreateCreate.kt
> +
이런것도 다른곳에서 사용할수도있을것같고 

4 이거 있잖아요

나중에 태그수가 많아질수도있고 size가 바뀔수도있는데 하드 코딩하는것보다 

전역변수 해놓은다음에

MAXIMUM_CHIP_COUNT = 4 라고 파일 맨위에나 설정파일에 정의해두고 꺼내다가 사용해야하지않나요?

2024-09-04 01:30 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/create/CreateCreate.kt
> +        }
이러한 확장자 는 따로 관리해야하지않나요??

이거 global이나 common이라는 구역에서 따로 관리하거나 

설정파일에서 확장자 지정해놓고 허용하는 확장자만 가져와서 for문 돌려서 확인해야될것같은데 

아니면 애초에 이런거 확인하는 메소드를 한곳에서 관리하고 꺼내서 쓰던지 해야할것같아요

2024-09-04 01:30 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/create/CreateCreate.kt
> +            storageDir /* 파일 저장 위치 */
궁금해서 그러는데 임시로 파일 만들어 놓는이유가뭐여요?

복사 해놓는거예요?

2024-09-04 01:30 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/create/CreateCreate_Adapter.kt
> +class CreateCreate_Adapter(private val items: MutableList<MediaItem>): RecyclerView.Adapter<CreateCreate_Adapter.CreateCreateAdapterViewHoler>() {
이건 카멜케이스랑 스네이크랑 합쳐놓은건가요?? CreateCreateAdapter 라고 안쓰고 _ 붙이는 이유가 궁금함

안드로이드는 원래 이런식?

2024-09-04 01:30 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/create/CreateCreate_Adapter.kt
> +    }
지금 boolean 변수에 대한 

명명법이 혼동되고있는데

does 와 is has 이런 동사로 시작하는게 좋긴한데

너무 혼동해서 사용하고있음

isVideoAvailable 이런식으로 

is로 boolean 값 변수를 통일하던가 그래야 가독성이 좀더 좋아보일것 같아요

이것도 보면 videoExists 와 doesVideoExist 이거의 차이가 뭔가요?

boolean값에 대한 변수명명에 일관성을 가집시다 

전 is로 통일하는편이긴해요

2024-09-05 00:40 UTC, daye200 commented on app/src/main/java/com/example/sul_game_frontend_practice1/create/CreateCreate_Adapter.kt
> +class CreateCreate_Adapter(private val items: MutableList<MediaItem>): RecyclerView.Adapter<CreateCreate_Adapter.CreateCreateAdapterViewHoler>() {
이게 createcreate 자체의 adapter가 아니라 그 안에 있는거라 구분하려고 했던건데 이상한가요?

2024-09-05 00:40 UTC, daye200 commented on app/src/main/java/com/example/sul_game_frontend_practice1/create/CreateCreate_Adapter.kt
> +    }
넹

2024-09-05 00:44 UTC, daye200 commented on app/src/main/java/com/example/sul_game_frontend_practice1/create/CreateCreate_Adapter.kt
> +    }
근데 저게 비디오가 존재하는지 유무랑 비디오인지 사진인지를 구분하기위해 다르게 썼던 걸로 기억해요

2024-09-05 00:45 UTC, daye200 commented on app/src/main/java/com/example/sul_game_frontend_practice1/create/CreateCreate.kt
> +
태그수가 많아지나요? 그럼 MAXIMUM_CHIP_COUNT = 4이케 바꾸도록 해보겠습니다

2024-09-05 00:49 UTC, daye200 commented on app/src/main/java/com/example/sul_game_frontend_practice1/create/CreateCreate.kt
> +            storageDir /* 파일 저장 위치 */
파일의 고유성을 보장하고, 데이터의 일시적인 저장과 처리를 쉽게 하며, 필요하지 않을 때는 간단히 삭제할 수 있어 효율적인 리소스 관리와 데이터 공유를 가능하게 한다고 gpt가 추천해줬어요

2024-09-05 01:05 UTC, daye200 commented on app/src/main/java/com/example/sul_game_frontend_practice1/create/CreateCreate_Adapter.kt
> +class CreateCreate_Adapter(private val items: MutableList<MediaItem>): RecyclerView.Adapter<CreateCreate_Adapter.CreateCreateAdapterViewHoler>() {
그래서 CreateCreateGameAdapter로 바꿀예정입니다!

2024-09-05 03:04 UTC, daye200 commented on app/src/main/java/com/example/sul_game_frontend_practice1/create/CreateCreate.kt
> +    }
그렇게 해볼게요!

2024-09-05 03:07 UTC, daye200 commented on app/src/main/java/com/example/sul_game_frontend_practice1/create/CreateCreate.kt
> +        }
위에 말한 FileUtil에 다 때려박으려 하는데 괜찮나요

2024-09-05 03:15 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/create/CreateCreate.kt
> +
많은건 아니고 이제 많아질수도있는거고

위에서 정의해두면

이제 굳이 코드를 안바꾸고 전역변수바꾸면되니까

2024-09-05 03:16 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/create/CreateCreate.kt
> +        }
> 위에 말한 FileUtil에 다 때려박으려 하는데 괜찮나요

그죠그죠 이름은 알아서 더 세분화시키려면 세분화시키도록하시고

나머지 파일안에 내용들은 잘 모르겠지만

지금 사용하는 로직들

다른곳에서도 충분히 사용할수있어서 한번 잘 팀원들도 쓸수있게 주석추가해도 좋고요 

global 폴더가 따로있나요?
common 폴더라던지

2024-09-05 03:17 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/create/CreateCreate.kt
> +            storageDir /* 파일 저장 위치 */
> 파일의 고유성을 보장하고, 데이터의 일시적인 저장과 처리를 쉽게 하며, 필요하지 않을 때는 간단히 삭제할 수 있어 효율적인 리소스 관리와 데이터 공유를 가능하게 한다고 gpt가 추천해줬어요

그렇군요

나중에 중간이 문제가 생기면 삭제하는 로직도 포함되어있나요?

2024-09-05 03:18 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/create/CreateCreate_Adapter.kt
> +class CreateCreate_Adapter(private val items: MutableList<MediaItem>): RecyclerView.Adapter<CreateCreate_Adapter.CreateCreateAdapterViewHoler>() {
> 그래서 CreateCreateGameAdapter로 바꿀예정입니다!

일단 이름이 직관적이지가않은데 ㅋㅋㅋㅋ

원래 이렁식으로 명명하나요?? 그냥 한눈보면 이 클래스가 뭐하는 클래스인지 느낌이 와야되는데 흠 .

2024-09-05 03:20 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/create/CreateCreate_Adapter.kt
> +    }
> 근데 저게 비디오가 존재하는지 유무랑 비디오인지 사진인지를 구분하기위해 다르게 썼던 걸로 기억해요

일단 이전로직을 잘 모르니까

비디오가 존재하는지 유무는 isVideoExists 가 직관적이고

사진인지 비디오인지 구분하는거는 

is 같은 Boolean값이 아니라 String 이 반환되어야하고

checkImageOrVideo 이런식으로 이름지으면 좋을것같은데

일단 메서드 명명을 메서드 이름보고 안헷갈리게 해봅시다

2024-09-05 09:45 UTC, daye200 commented on app/src/main/java/com/example/sul_game_frontend_practice1/create/CreateCreate_Adapter.kt
> +class CreateCreate_Adapter(private val items: MutableList<MediaItem>): RecyclerView.Adapter<CreateCreate_Adapter.CreateCreateAdapterViewHoler>() {
이거 프론트는 모두가 알아듣긴해요..

2024-09-05 09:50 UTC, daye200 commented on app/src/main/java/com/example/sul_game_frontend_practice1/create/CreateCreate.kt
> +        }
common폴더 만들고 안에 넣어 놓겠습니다

2024-09-05 09:51 UTC, daye200 commented on app/src/main/java/com/example/sul_game_frontend_practice1/create/CreateCreate_Adapter.kt
> +    }
image인가요 이면 boolean이 아닌가요?

2024-09-05 09:51 UTC, daye200 commented on app/src/main/java/com/example/sul_game_frontend_practice1/create/CreateCreate.kt
> +            storageDir /* 파일 저장 위치 */
어떤 문제가 발생하나요

2024-09-05 09:51 UTC, daye200 commented on app/src/main/java/com/example/sul_game_frontend_practice1/create/CreateCreate.kt
> +
넹

2024-09-05 10:59 UTC, daye200 commented on app/src/main/java/com/example/sul_game_frontend_practice1/create/CreateCreate_Adapter.kt
> +    }
IsVideoExists랑 IsVideo로 바꿨는데 괜찮나요

2024-09-07 12:32 UTC, merged