feat(mypage): 디자인 수정 및 통신 부분 개선
Sul-Game-Wiki/Sul-Game-Frontend pull request #25
Opened 2024-09-05 11:19 UTC by cloudyGaha

2024-09-05 16:07 UTC, Cassiiopeia requested changes

2024-09-05 16:07 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/MainActivity.kt
> +            binding.tvUniversityMypage.text = member.college
죄송합니다 이거 university 로 이름 바꿔서갈듯요

전체적으로 college라는 표현 안씆니다

2024-09-05 16:07 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/MainActivity.kt
> +            val defaultImage = R.color.light_gray
이거 이제 game 상세보기에서 댓글 프로필 이미지 표시할때 사용할수도있을것같네요

다른 사람글이 사용할수있도록 공통적인 파일관리 로직에 넣을수도있을것같네요 한번 common쪽으로 다예가 만들어놨다는데 폴더

거기에 ImageUtil 만들고 여기다가 메소드 만들고 주석으로 어떤걸한다 표시하는것도 좋아보이네요

2024-09-05 16:38 UTC, Cassiiopeia requested changes
음 많은 부분이 있네요

다음주턴 PR주기 더 짧게

기능 하나 완료하면 바로 PR 올려주세요

이거 리뷰하기 너무힘듬

놓친부분 많은것같고

그리고 서로 Log 메시지가있잖아요

이거 서로 안정해놓나요???

Log.e() 앞에 들어가는 제목에 술겜위키

뭐 이런식으로 뭐 정해놓는 그런 문화없나요?

그리고 global적인부분은 따로 빼야될걱같아요

지금 다른사람이 만든거보면 거기있는거랑 메소드 방향성이 비슷해보이기도해요

그리고 API 부분만 로깅처리해놓았던데

그냥 로직부분도 중요부분에 로깅처리하면 더 디버깅하기좋을것같구요

2024-09-05 16:38 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/MainActivity.kt
>      override fun onCreate(savedInstanceState: Bundle?) {
메서드만 보고 이게 무엇을 의미하는지 모르겠어요

onCreate 무엇을 만드는??

initEvent 무엇의 처음이벤트??

onSlide?? 어떤슬라이드? 슬라이드가 하나면 상관없을텐데

코드만 보고 바로 직관적으로 아무것도 모르겠네요

2024-09-05 16:38 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/MainActivity.kt
> +            NetworkManager.updateNickname(binding.et1Editprofile.text.toString(), this)
NetworkManager는 무슨 네트워크죠?? 궁금해서요

2024-09-05 16:38 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/MainActivity.kt
> +    private fun updateUIWithMemberData() {
이런 직관적인 메소드이름 good

2024-09-05 16:38 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/MainActivity.kt
> +        // 목업 데이터 추가
목업데이터는 다른 메소드로 나누는게 더 객체지향적일것같긴한데요

흠... 임시부분이라 그런라 애매하네요

2024-09-05 16:38 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/MainActivity.kt
> +    private fun requestPermissions() {
이런건 global로 따로 같이 쓰는함수아닌가요?

이렇게 따로 있어오 괜찮은건아요??

어떤 permission 요구라는지 메소드에도 있으면 놓을것같기도하고요

2024-09-05 16:38 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/MainActivity.kt
> +    private fun openGallery() {
이것도 다예가 쓸것같은데

2024-09-05 16:38 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/MainActivity.kt
> +        startActivityForResult(intent, REQUEST_IMAGE_GALLERY)
이거 사소한건데 intent 변수가 필요하나요? 그냥 합쳐버리는게 깔끔하고 낫지않아요?

지금 보여서하는말이긴합니다

위에도 이렇게 불필요한 변수 선언은 합치는게 더 깔끔하고 컴팩트할것같아요

백도 이제 익숙하지 않을때는 각각 나눠서 썼었는데

이제 나중가면 뭐 반환할지 딱 잘 보이게되니
컴팩트하게 합쳐서 쓰는쪽으로 했습니다

2024-09-05 16:38 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/MainActivity.kt
> +    @SuppressLint("QueryPermissionsNeeded")
무슨 어노테이션인가요? 궁금해서

2024-09-05 16:38 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/MainActivity.kt
> +    private fun updateProfileImage(imageFile : File){
궁금한데 이 메소드는 왜 있는거예요?? 똑같지않아요?

2024-09-05 16:38 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/MainActivity.kt
> +    private fun getRealPathFromURI(uri: Uri): String {
URI는 뭔가요?? 가짜 파일경로인가요?? 임시파일경로??

2024-09-05 16:38 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/MainActivity.kt
> +    private fun convertBitmapToFile(bitmap: Bitmap): File {
이거 다예코드에 임시로 이미지 만드는거 있었거든요??

그거랑 차이점이 뭔가요

그것도 temp 이미지 만들던데

여기도네요

bit는 어디에서 다루는거죠?? 왜 꼭 jpg인가요??

2024-09-05 16:38 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/MainActivity.kt
> +        val bottomSheetTitle = arrayListOf<String>("마이 페이지", "내 게시글", "즐겨찾기 게시글", "좋아요 게시글", "계정 설정")
이건 여기에서 list 만들어서 넣는것보다

유지보수성이 편하게

파일 맨 위에서 static 한  list 를 만들거나

따로 Enum 클래스를 만들어서 가져와서 관리하거나 하는게좋을것같은데요

이부분 변경하려고 하면 찾으러 다니면서 헤멜것같아요

2024-09-05 16:38 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/mypage/BookmarkedPostAdapter.kt
>      inner class FavorPostHolder(binding: ItemFavorpostRecyclerviewBinding) : RecyclerView.ViewHolder(binding.root) {
Favor 오타인가요?

2024-09-05 16:38 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/retrofit/NetworkManager.kt
> +object NetworkManager {
이건 각각 따로관리하나요??

좀 세분화해서 이제

MemberProfileNetWorkManager 이런식으로 해야하는건가요??

다들 network manager라는 단를 사용하면서 여기에서 통신하나요??

일단 명명법 통합이 필요해보이고

서로에게 말해야서 합의해야될것같은데요?

2024-09-05 16:38 UTC, Cassiiopeia commented on app/src/main/java/com/example/sul_game_frontend_practice1/retrofit/RetrofitClient.kt
> +
이것도 궁금한디

다들 이거 가져다쓸텐데 각각 따러 관리해여??

2024-09-06 10:12 UTC, daye200 commented on app/src/main/java/com/example/sul_game_frontend_practice1/MainActivity.kt
> +            NetworkManager.updateNickname(binding.et1Editprofile.text.toString(), this)
저두요

2024-09-06 10:12 UTC, daye200 commented on app/src/main/java/com/example/sul_game_frontend_practice1/MainActivity.kt
> +            binding.et1Editprofile.setText(member.nickname)
이거 아이디가 et1,2,3,4인부분 수정하는게 나을거 같아요

2024-09-06 10:12 UTC, daye200 commented on app/src/main/java/com/example/sul_game_frontend_practice1/MainActivity.kt
> +    private fun openGallery() {
비슷한 코드가 있는데 따로 빼 놓는게 나을까요?

2024-09-07 03:03 UTC, hwan04 commented on app/src/main/java/com/example/sul_game_frontend_practice1/mypage/LikedPostAdapter.kt
> +        holder.tvSentence.text = item[position].introduction
view 이름이랑 item의 이름을 맞추는 것이 어떨까용? 
ex) introduction -> sentence 이렇게 두 개가 똑같은 것이 보기 편할 것 같습니다.

2024-09-07 03:03 UTC, hwan04 commented on app/src/main/res/layout/layout_mypage.xml
android:text=""와 android:src=""처럼 view에 임시 값들을 넣어주는 부분들은 android: 대신에 tools:를 사용하는게 어떤가용?

2024-09-08 14:04 UTC, cloudyGaha commented on app/src/main/java/com/example/sul_game_frontend_practice1/MainActivity.kt
> +            binding.tvUniversityMypage.text = member.college
확인했습니다!

2024-09-08 14:05 UTC, cloudyGaha commented on app/src/main/java/com/example/sul_game_frontend_practice1/MainActivity.kt
> +            val defaultImage = R.color.light_gray
그 방향으로 진행해볼게요!

2024-09-08 14:07 UTC, cloudyGaha commented on app/src/main/java/com/example/sul_game_frontend_practice1/MainActivity.kt
>      override fun onCreate(savedInstanceState: Bundle?) {
initEvent는 화면 초기화 시 호출되는 함수인데 좀 더 명확하게 이름 바꾸고, onCreate나 onSlide는 내장 함수인데 주석 달아놓을게요!

2024-09-08 14:08 UTC, cloudyGaha commented on app/src/main/java/com/example/sul_game_frontend_practice1/MainActivity.kt
> +            NetworkManager.updateNickname(binding.et1Editprofile.text.toString(), this)
NetworkManager는 Retrofit 통신부분 함수를 따로 모아놓은 파일인데 파일 안에 주석 달아놓을게요!

2024-09-08 14:08 UTC, cloudyGaha commented on app/src/main/java/com/example/sul_game_frontend_practice1/MainActivity.kt
> +    private fun updateUIWithMemberData() {
다른 함수 작명할때 참고하겠습니다

2024-09-08 14:10 UTC, cloudyGaha commented on app/src/main/java/com/example/sul_game_frontend_practice1/MainActivity.kt
> +    private fun requestPermissions() {
앱 시작 또는 카메라, 파일 사용 시 사용되는 함수여서 사용되는 곳에 정의한 것인데, 한 번 찾아볼게여

2024-09-08 14:13 UTC, cloudyGaha commented on app/src/main/java/com/example/sul_game_frontend_practice1/MainActivity.kt
> +    private fun convertBitmapToFile(bitmap: Bitmap): File {
카메라로 촬영한 것을 jpg 파일로 변환하여 서버 업로드를 위한 함수인데, 차이는 없을 것 같아요. jpg 포맷이 보편적이라 생각해서 jpg로 했습니다.

2024-09-08 14:13 UTC, cloudyGaha commented on app/src/main/java/com/example/sul_game_frontend_practice1/MainActivity.kt
> +        val bottomSheetTitle = arrayListOf<String>("마이 페이지", "내 게시글", "즐겨찾기 게시글", "좋아요 게시글", "계정 설정")
좋은 생각 같습니다. 나중에 바꿔볼게요

2024-09-08 14:14 UTC, cloudyGaha commented on app/src/main/java/com/example/sul_game_frontend_practice1/mypage/BookmarkedPostAdapter.kt
>      inner class FavorPostHolder(binding: ItemFavorpostRecyclerviewBinding) : RecyclerView.ViewHolder(binding.root) {
맨 처음에 백엔드 생각안하고 만든 것이라서 확인 못했는데 바꾸겠습니다

2024-09-08 14:15 UTC, cloudyGaha commented on app/src/main/java/com/example/sul_game_frontend_practice1/MainActivity.kt
> +            binding.et1Editprofile.setText(member.nickname)
수정하겠습니다

2024-09-08 14:18 UTC, cloudyGaha commented on app/src/main/java/com/example/sul_game_frontend_practice1/retrofit/NetworkManager.kt
> +object NetworkManager {
따로 관리 하고 있는 것 같은데 나중에 합의해야겠네요

2024-09-08 14:19 UTC, cloudyGaha commented on app/src/main/java/com/example/sul_game_frontend_practice1/MainActivity.kt
> +        startActivityForResult(intent, REQUEST_IMAGE_GALLERY)
코드가 길어보이기도 하고 좀 더 명확해 보인다고 생각했는데, 주석 달고 합쳐보겠습니다

2024-09-08 14:21 UTC, cloudyGaha commented on app/src/main/java/com/example/sul_game_frontend_practice1/MainActivity.kt
> +    @SuppressLint("QueryPermissionsNeeded")
Android 앱에서 특정 권한 경고를 무시하도록 안드로이드 스튜디오 코드 검사 도구에 지시하는 어노테이션입니다

2024-09-08 14:21 UTC, cloudyGaha commented on app/src/main/java/com/example/sul_game_frontend_practice1/MainActivity.kt
> +    private fun openGallery() {
거의 똑같은 용도로 사용할거라 빼놓고 같이 사용하는게 맞는것 같아요

2024-09-08 14:22 UTC, cloudyGaha commented on app/src/main/res/layout/layout_mypage.xml
오 좋네요 수정하겠습니다

2024-09-08 14:23 UTC, cloudyGaha commented on app/src/main/java/com/example/sul_game_frontend_practice1/mypage/LikedPostAdapter.kt
> +        holder.tvSentence.text = item[position].introduction
넵넵

2024-09-08 14:30 UTC, daye200 commented on app/src/main/java/com/example/sul_game_frontend_practice1/retrofit/RetrofitClient.kt
> +
이거 하나로 만들고 그걸로 다같이 이용할거 같아요!

2024-09-08 14:30 UTC, daye200 commented on app/src/main/java/com/example/sul_game_frontend_practice1/MainActivity.kt
> +    private fun requestPermissions() {
permission비슷한 코드가 있어서 나중에 빼놓을거 같습니다

2024-09-11 05:41 UTC, merged